/*

 BACKGROUNDMAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 64
   Tile set      : BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMap3Width 64
#define BackgroundMap3Height 64
#define BackgroundMap3Bank 0

extern unsigned char BackgroundMap3[];

/* End of BACKGROUNDMAP3.H */
